/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author منار
 */
public class Browse_Services extends javax.swing.JFrame {

    /**
     * Creates new form Browse_Services
     */
    public Browse_Services() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        View_Services = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Products = new javax.swing.JLabel();
        Make_Appointment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 249, 249));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("Hello, ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 60, 136, 75);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 102));
        jLabel3.setText("choose what you want");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 130, 340, 37);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("View Services");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 360, 124, 22);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Service_Icon.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 230, 96, 120);

        View_Services.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/square_purple.png"))); // NOI18N
        View_Services.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View_ServicesMouseClicked(evt);
            }
        });
        jPanel1.add(View_Services);
        View_Services.setBounds(10, 230, 149, 194);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Product");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(220, 360, 90, 22);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/App_Icon.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 450, 96, 130);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Make Appointment ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(80, 580, 175, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Product_Icon.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(210, 240, 92, 93);

        Products.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Square_Pink.png"))); // NOI18N
        Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsMouseClicked(evt);
            }
        });
        jPanel1.add(Products);
        Products.setBounds(180, 230, 150, 190);

        Make_Appointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/App_Box.png"))); // NOI18N
        Make_Appointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Make_AppointmentMouseClicked(evt);
            }
        });
        jPanel1.add(Make_Appointment);
        Make_Appointment.setBounds(10, 460, 330, 170);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void View_ServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View_ServicesMouseClicked
        // TODO add your handling code here:
        //Not implemented yet

    }//GEN-LAST:event_View_ServicesMouseClicked

    private void ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsMouseClicked
        // TODO add your handling code here:
        BuyProducts X = new BuyProducts();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductsMouseClicked

    private void Make_AppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Make_AppointmentMouseClicked
        // TODO add your handling code here:
        MakeAppointment X = null;
        try {
            X = new MakeAppointment();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Browse_Services.class.getName()).log(Level.SEVERE, null, ex);
        }
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Make_AppointmentMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Browse_Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Browse_Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Browse_Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Browse_Services.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Browse_Services().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Make_Appointment;
    private javax.swing.JLabel Products;
    private javax.swing.JLabel View_Services;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
