/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

import static ProgramPackage.BuyProducts.o;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author renad
 */
public class Cart extends javax.swing.JFrame {

    ImageIcon delete = new ImageIcon("src\\Icons\\delete.png");
    
    /**
     * Creates new form Cart
     */
    public Cart() {
        initComponents();

        if (o != null) {
            disblayProduct(o.getSelectedProducts());
            disblayTotal(o.getTotalPrice());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Gray = new javax.swing.JPanel();
        Background_White = new javax.swing.JPanel();
        Home_Icon_Label = new javax.swing.JLabel();
        Cart_Icon = new javax.swing.JLabel();
        PageTitle_Label = new javax.swing.JLabel();
        AmountTitle = new javax.swing.JLabel();
        ProductTitle = new javax.swing.JLabel();
        errorr_empty = new javax.swing.JLabel();
        First_product_added = new javax.swing.JLabel();
        sec_product_added = new javax.swing.JLabel();
        Third_product_added = new javax.swing.JLabel();
        Fourth_product_added = new javax.swing.JLabel();
        PriceTitle = new javax.swing.JLabel();
        totalPrice = new javax.swing.JLabel();
        ConfirmButton = new javax.swing.JButton();
        Back_label = new javax.swing.JLabel();
        inc_first_product = new javax.swing.JLabel();
        Amount_1 = new javax.swing.JLabel();
        Amount_2 = new javax.swing.JLabel();
        Amount_3 = new javax.swing.JLabel();
        Amount_4 = new javax.swing.JLabel();
        inc_second_product = new javax.swing.JLabel();
        dec_first_product = new javax.swing.JLabel();
        dec_second_product = new javax.swing.JLabel();
        inc_third_product = new javax.swing.JLabel();
        inc_fourth_product = new javax.swing.JLabel();
        dec_third_product = new javax.swing.JLabel();
        dec_fourth_product = new javax.swing.JLabel();
        delete_product_1 = new javax.swing.JLabel();
        delete_product_2 = new javax.swing.JLabel();
        delete_product_3 = new javax.swing.JLabel();
        delete_product_4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Background_Gray.setBackground(new java.awt.Color(249, 249, 249));
        Background_Gray.setLayout(null);

        Background_White.setBackground(new java.awt.Color(255, 255, 255));

        Home_Icon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        Home_Icon_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_Icon_LabelMouseClicked(evt);
            }
        });

        Cart_Icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cart_dark.png"))); // NOI18N

        javax.swing.GroupLayout Background_WhiteLayout = new javax.swing.GroupLayout(Background_White);
        Background_White.setLayout(Background_WhiteLayout);
        Background_WhiteLayout.setHorizontalGroup(
            Background_WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_WhiteLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(Cart_Icon)
                .addGap(54, 54, 54)
                .addComponent(Home_Icon_Label)
                .addGap(165, 165, 165))
        );
        Background_WhiteLayout.setVerticalGroup(
            Background_WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_WhiteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Background_WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cart_Icon)
                    .addComponent(Home_Icon_Label))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        Background_Gray.add(Background_White);
        Background_White.setBounds(0, 600, 380, 110);

        PageTitle_Label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PageTitle_Label.setForeground(new java.awt.Color(91, 74, 132));
        PageTitle_Label.setText("Cart");
        Background_Gray.add(PageTitle_Label);
        PageTitle_Label.setBounds(30, 60, 70, 37);

        AmountTitle.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AmountTitle.setForeground(new java.awt.Color(91, 74, 132));
        AmountTitle.setText("Amount");
        Background_Gray.add(AmountTitle);
        AmountTitle.setBounds(290, 160, 50, 16);

        ProductTitle.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ProductTitle.setForeground(new java.awt.Color(91, 74, 132));
        ProductTitle.setText("Products");
        Background_Gray.add(ProductTitle);
        ProductTitle.setBounds(30, 160, 60, 16);

        errorr_empty.setFont(new java.awt.Font("Dubai", 0, 14)); // NOI18N
        errorr_empty.setForeground(new java.awt.Color(255, 102, 102));
        errorr_empty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        errorr_empty.setText("  ");
        Background_Gray.add(errorr_empty);
        errorr_empty.setBounds(0, 350, 380, 24);

        First_product_added.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        First_product_added.setForeground(new java.awt.Color(51, 51, 51));
        First_product_added.setText("Prouduct 1");
        Background_Gray.add(First_product_added);
        First_product_added.setBounds(30, 200, 220, 17);

        sec_product_added.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sec_product_added.setForeground(new java.awt.Color(51, 51, 51));
        sec_product_added.setText("Prouduct 2");
        Background_Gray.add(sec_product_added);
        sec_product_added.setBounds(30, 240, 220, 17);

        Third_product_added.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Third_product_added.setForeground(new java.awt.Color(51, 51, 51));
        Third_product_added.setText("Prouduct 3");
        Background_Gray.add(Third_product_added);
        Third_product_added.setBounds(30, 280, 220, 17);

        Fourth_product_added.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fourth_product_added.setForeground(new java.awt.Color(51, 51, 51));
        Fourth_product_added.setText("Prouduct 4");
        Background_Gray.add(Fourth_product_added);
        Fourth_product_added.setBounds(30, 320, 220, 17);

        PriceTitle.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        PriceTitle.setForeground(new java.awt.Color(91, 74, 132));
        PriceTitle.setText("Total :");
        Background_Gray.add(PriceTitle);
        PriceTitle.setBounds(30, 510, 60, 16);

        totalPrice.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totalPrice.setForeground(new java.awt.Color(243, 130, 89));
        totalPrice.setText("Total Price");
        Background_Gray.add(totalPrice);
        totalPrice.setBounds(30, 550, 80, 20);

        ConfirmButton.setBackground(new java.awt.Color(121, 99, 175));
        ConfirmButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmButton.setText("Next");
        ConfirmButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmButtonconfirm(evt);
            }
        });
        Background_Gray.add(ConfirmButton);
        ConfirmButton.setBounds(260, 510, 100, 50);

        Back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_arrow.png"))); // NOI18N
        Back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backTo_buyProduct(evt);
            }
        });
        Background_Gray.add(Back_label);
        Back_label.setBounds(10, 20, 14, 24);

        inc_first_product.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inc_first_product.setForeground(new java.awt.Color(91, 74, 132));
        inc_first_product.setText("+");
        inc_first_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inc_first_productMouseClicked(evt);
            }
        });
        Background_Gray.add(inc_first_product);
        inc_first_product.setBounds(280, 200, 15, 17);

        Amount_1.setText("1");
        Amount_1.setPreferredSize(new java.awt.Dimension(6, 17));
        Background_Gray.add(Amount_1);
        Amount_1.setBounds(310, 200, 16, 17);

        Amount_2.setText("1");
        Amount_2.setPreferredSize(new java.awt.Dimension(6, 17));
        Background_Gray.add(Amount_2);
        Amount_2.setBounds(310, 240, 16, 17);

        Amount_3.setText("1");
        Amount_3.setPreferredSize(new java.awt.Dimension(6, 17));
        Background_Gray.add(Amount_3);
        Amount_3.setBounds(310, 280, 16, 17);

        Amount_4.setText("1");
        Amount_4.setPreferredSize(new java.awt.Dimension(6, 17));
        Background_Gray.add(Amount_4);
        Amount_4.setBounds(310, 320, 16, 17);

        inc_second_product.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inc_second_product.setForeground(new java.awt.Color(91, 74, 132));
        inc_second_product.setText("+");
        inc_second_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inc_second_productMouseClicked(evt);
            }
        });
        Background_Gray.add(inc_second_product);
        inc_second_product.setBounds(280, 240, 15, 17);

        dec_first_product.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dec_first_product.setForeground(new java.awt.Color(91, 74, 132));
        dec_first_product.setText("-");
        dec_first_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dec_first_productMouseClicked(evt);
            }
        });
        Background_Gray.add(dec_first_product);
        dec_first_product.setBounds(340, 200, 15, 17);

        dec_second_product.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dec_second_product.setForeground(new java.awt.Color(91, 74, 132));
        dec_second_product.setText("-");
        dec_second_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dec_second_productMouseClicked(evt);
            }
        });
        Background_Gray.add(dec_second_product);
        dec_second_product.setBounds(340, 240, 15, 17);

        inc_third_product.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inc_third_product.setForeground(new java.awt.Color(91, 74, 132));
        inc_third_product.setText("+");
        inc_third_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inc_third_productMouseClicked(evt);
            }
        });
        Background_Gray.add(inc_third_product);
        inc_third_product.setBounds(280, 280, 15, 17);

        inc_fourth_product.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inc_fourth_product.setForeground(new java.awt.Color(91, 74, 132));
        inc_fourth_product.setText("+");
        inc_fourth_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inc_fourth_productMouseClicked(evt);
            }
        });
        Background_Gray.add(inc_fourth_product);
        inc_fourth_product.setBounds(280, 320, 15, 17);

        dec_third_product.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dec_third_product.setForeground(new java.awt.Color(91, 74, 132));
        dec_third_product.setText("-");
        dec_third_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dec_third_productMouseClicked(evt);
            }
        });
        Background_Gray.add(dec_third_product);
        dec_third_product.setBounds(340, 280, 15, 17);

        dec_fourth_product.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dec_fourth_product.setForeground(new java.awt.Color(91, 74, 132));
        dec_fourth_product.setText("-");
        dec_fourth_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dec_fourth_productMouseClicked(evt);
            }
        });
        Background_Gray.add(dec_fourth_product);
        dec_fourth_product.setBounds(340, 320, 15, 17);

        delete_product_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        delete_product_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_product_1MouseClicked(evt);
            }
        });
        Background_Gray.add(delete_product_1);
        delete_product_1.setBounds(10, 200, 10, 20);

        delete_product_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        delete_product_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_product_2MouseClicked(evt);
            }
        });
        Background_Gray.add(delete_product_2);
        delete_product_2.setBounds(10, 240, 10, 20);

        delete_product_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        delete_product_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_product_3MouseClicked(evt);
            }
        });
        Background_Gray.add(delete_product_3);
        delete_product_3.setBounds(10, 280, 10, 20);

        delete_product_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete.png"))); // NOI18N
        delete_product_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_product_4MouseClicked(evt);
            }
        });
        Background_Gray.add(delete_product_4);
        delete_product_4.setBounds(10, 320, 10, 20);

        getContentPane().add(Background_Gray);
        Background_Gray.setBounds(0, 0, 380, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void disblayProduct(ArrayList<Product> productList) {
        javax.swing.JLabel[] p = {First_product_added, sec_product_added, Third_product_added, Fourth_product_added};
        javax.swing.JLabel[] del = {delete_product_1, delete_product_2, delete_product_3, delete_product_4};
        javax.swing.JLabel[] inc = {inc_first_product, inc_second_product, inc_third_product, inc_fourth_product};
        javax.swing.JLabel[] dec = {dec_first_product, dec_second_product, dec_third_product, dec_fourth_product};
        javax.swing.JLabel[] amount = {Amount_1, Amount_2, Amount_3, Amount_4};
        
        resetLabels(p, del, inc, dec, amount);

        for (int i = 0; i < productList.size(); i++) {
            p[i].setText(productList.get(i).getName() + "    " + productList.get(i).getPrice());
            amount[i].setText(productList.get(i).getAmount() + "");
            inc[i].setText("+");
            dec[i].setText("-");
            del[i].setIcon(delete);
        }
    }

    private void resetLabels(JLabel[] p, JLabel[] del, JLabel[] inc, JLabel[] dec, JLabel[] amount) {
        for (int i = 0; i < p.length; i++) {
            p[i].setText("");
            del[i].setIcon(null);
            inc[i].setText("");
            dec[i].setText("");
            amount[i].setText("");
        }
    }

    private void disblayTotal(int price) {
        totalPrice.setText(price + " SR");

    }

    private void ConfirmButtonconfirm(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmButtonconfirm

        if (o.getTotalPrice() != 0) {
            Date_Time x = new Date_Time();
            x.setVisible(true);
            this.dispose();
        } else {
            errorr_empty.setText("you most add Product to continue");
        }

    }//GEN-LAST:event_ConfirmButtonconfirm

    private void backTo_buyProduct(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backTo_buyProduct
        BuyProducts b = new BuyProducts();
        b.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backTo_buyProduct
    public int increment_amount(Product p) {
        int amount = p.getAmount();
        amount++;
        p.setAmount(amount);
        return amount;
    }

    public int decrement_amount(Product p) {
        int amount = p.getAmount();
        if (amount > 0) {
            amount--;
            p.setAmount(amount);
        }
        return amount;
    }
    
    public void delete_product(Product p){
        o.removeProduct(p);
    }


    private void inc_first_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inc_first_productMouseClicked

        if (o.getSelectedProducts().get(0).getAmount() < 10) {

            int total_1 = (increment_amount(o.getSelectedProducts().get(0)));

            o.getSelectedProducts().get(0).setAmount(total_1);

            o.setTotalPrice();
            Amount_1.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }


    }//GEN-LAST:event_inc_first_productMouseClicked

    private void inc_second_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inc_second_productMouseClicked

        if (o.getSelectedProducts().get(1).getAmount() < 10) {

            int total_1 = (increment_amount(o.getSelectedProducts().get(1)));

            o.getSelectedProducts().get(1).setAmount(total_1);

            o.setTotalPrice();
            Amount_2.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }


    }//GEN-LAST:event_inc_second_productMouseClicked

    private void dec_first_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dec_first_productMouseClicked
        if (o.getSelectedProducts().get(0).getAmount() > 1) {

            int total_1 = (decrement_amount(o.getSelectedProducts().get(0)));

            o.getSelectedProducts().get(0).setAmount(total_1);

            o.setTotalPrice();
            Amount_1.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }


    }//GEN-LAST:event_dec_first_productMouseClicked

    private void dec_second_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dec_second_productMouseClicked
        if (o.getSelectedProducts().get(1).getAmount() > 1) {

            int total_1 = (decrement_amount(o.getSelectedProducts().get(1)));

            o.getSelectedProducts().get(1).setAmount(total_1);

            o.setTotalPrice();
            Amount_2.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }
    }//GEN-LAST:event_dec_second_productMouseClicked

    private void inc_third_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inc_third_productMouseClicked
        if (o.getSelectedProducts().get(2).getAmount() < 10) {

            int total_1 = (increment_amount(o.getSelectedProducts().get(2)));

            o.getSelectedProducts().get(2).setAmount(total_1);

            o.setTotalPrice();
            Amount_3.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }
    }//GEN-LAST:event_inc_third_productMouseClicked

    private void inc_fourth_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inc_fourth_productMouseClicked
        if (o.getSelectedProducts().get(3).getAmount() < 10) {

            int total_1 = (increment_amount(o.getSelectedProducts().get(3)));

            o.getSelectedProducts().get(3).setAmount(total_1);

            o.setTotalPrice();
            Amount_4.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }
    }//GEN-LAST:event_inc_fourth_productMouseClicked

    private void dec_third_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dec_third_productMouseClicked
        if (o.getSelectedProducts().get(2).getAmount() > 1) {

            int total_1 = (decrement_amount(o.getSelectedProducts().get(2)));

            o.getSelectedProducts().get(2).setAmount(total_1);

            o.setTotalPrice();
            Amount_3.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }
    }//GEN-LAST:event_dec_third_productMouseClicked

    private void dec_fourth_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dec_fourth_productMouseClicked
        if (o.getSelectedProducts().get(3).getAmount() > 1) {

            int total_1 = (decrement_amount(o.getSelectedProducts().get(3)));

            o.getSelectedProducts().get(3).setAmount(total_1);

            o.setTotalPrice();
            Amount_4.setText(total_1 + "");

            disblayTotal(o.getTotalPrice());
        }
    }//GEN-LAST:event_dec_fourth_productMouseClicked

    private void delete_product_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_product_1MouseClicked
        delete_product(o.getSelectedProducts().get(0));
        disblayProduct(o.getSelectedProducts());
        disblayTotal(o.getTotalPrice());
    }//GEN-LAST:event_delete_product_1MouseClicked

    private void delete_product_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_product_2MouseClicked
        delete_product(o.getSelectedProducts().get(1));
        disblayProduct(o.getSelectedProducts());
        disblayTotal(o.getTotalPrice());
    }//GEN-LAST:event_delete_product_2MouseClicked

    private void delete_product_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_product_3MouseClicked
        delete_product(o.getSelectedProducts().get(2));
        disblayProduct(o.getSelectedProducts());
        disblayTotal(o.getTotalPrice());
    }//GEN-LAST:event_delete_product_3MouseClicked

    private void delete_product_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_product_4MouseClicked
        delete_product(o.getSelectedProducts().get(3));
        disblayProduct(o.getSelectedProducts());
        disblayTotal(o.getTotalPrice());
    }//GEN-LAST:event_delete_product_4MouseClicked

    private void Home_Icon_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_Icon_LabelMouseClicked
        // TODO add your handling code here:
        
        
         Browse_Services X = new Browse_Services();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Home_Icon_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountTitle;
    private javax.swing.JLabel Amount_1;
    private javax.swing.JLabel Amount_2;
    private javax.swing.JLabel Amount_3;
    private javax.swing.JLabel Amount_4;
    private javax.swing.JLabel Back_label;
    private javax.swing.JPanel Background_Gray;
    private javax.swing.JPanel Background_White;
    private javax.swing.JLabel Cart_Icon;
    private javax.swing.JButton ConfirmButton;
    private javax.swing.JLabel First_product_added;
    private javax.swing.JLabel Fourth_product_added;
    private javax.swing.JLabel Home_Icon_Label;
    private javax.swing.JLabel PageTitle_Label;
    private javax.swing.JLabel PriceTitle;
    private javax.swing.JLabel ProductTitle;
    private javax.swing.JLabel Third_product_added;
    private javax.swing.JLabel dec_first_product;
    private javax.swing.JLabel dec_fourth_product;
    private javax.swing.JLabel dec_second_product;
    private javax.swing.JLabel dec_third_product;
    private javax.swing.JLabel delete_product_1;
    private javax.swing.JLabel delete_product_2;
    private javax.swing.JLabel delete_product_3;
    private javax.swing.JLabel delete_product_4;
    private javax.swing.JLabel errorr_empty;
    private javax.swing.JLabel inc_first_product;
    private javax.swing.JLabel inc_fourth_product;
    private javax.swing.JLabel inc_second_product;
    private javax.swing.JLabel inc_third_product;
    private javax.swing.JLabel sec_product_added;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables

}
