/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author renad
 */
public class ConfirmAppointment extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation_Button
     */
    public ConfirmAppointment() {
        initComponents();

       
        // display appointment informations
        Appointment appointment = MakeAppointment.client_appointment;
        BetsNo_Label.setText(appointment.PetsNo());
        Date_Label.setText(appointment.Date());
        Time_Label.setText(appointment.time());
        Services_Label.setText(appointment.services());
        TotalPrice_Label.setText("Total Price : " + appointment.getTotalPrice() + " SR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmationBackground_Panel = new javax.swing.JPanel();
        Confirmation_Button = new javax.swing.JButton();
        Page_Title_Label = new javax.swing.JLabel();
        Appointment_Info_Label = new javax.swing.JLabel();
        BetsNo_Label = new javax.swing.JLabel();
        Date_Label = new javax.swing.JLabel();
        Time_Label = new javax.swing.JLabel();
        Services_Label = new javax.swing.JLabel();
        TotalPrice_Label = new javax.swing.JLabel();
        backToprevious = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ConfirmationBackground_Panel.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmationBackground_Panel.setEnabled(false);
        ConfirmationBackground_Panel.setMinimumSize(new java.awt.Dimension(690, 450));
        ConfirmationBackground_Panel.setPreferredSize(new java.awt.Dimension(550, 550));

        Confirmation_Button.setBackground(new java.awt.Color(121, 99, 175));
        Confirmation_Button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Confirmation_Button.setForeground(new java.awt.Color(255, 255, 255));
        Confirmation_Button.setText("Confirm");
        Confirmation_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToPayment(evt);
            }
        });

        Page_Title_Label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Page_Title_Label.setText("Confirm Appointment");

        Appointment_Info_Label.setText("Appointment Information:");

        BetsNo_Label.setText("BetsNo");

        Date_Label.setText("Date");

        Time_Label.setText("Time");

        Services_Label.setText("Services");

        TotalPrice_Label.setText("Total Price");

        backToprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        backToprevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToprevious(evt);
            }
        });

        javax.swing.GroupLayout ConfirmationBackground_PanelLayout = new javax.swing.GroupLayout(ConfirmationBackground_Panel);
        ConfirmationBackground_Panel.setLayout(ConfirmationBackground_PanelLayout);
        ConfirmationBackground_PanelLayout.setHorizontalGroup(
            ConfirmationBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                .addGroup(ConfirmationBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backToprevious)
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(TotalPrice_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Page_Title_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(BetsNo_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Date_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Time_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Services_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(Appointment_Info_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(Confirmation_Button)))
                .addGap(187, 187, 187))
        );
        ConfirmationBackground_PanelLayout.setVerticalGroup(
            ConfirmationBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                .addGroup(ConfirmationBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backToprevious)
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(TotalPrice_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Page_Title_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(BetsNo_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(Date_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(Time_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(Services_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(Appointment_Info_Label))
                    .addGroup(ConfirmationBackground_PanelLayout.createSequentialGroup()
                        .addGap(287, 287, 287)
                        .addComponent(Confirmation_Button)))
                .addGap(236, 236, 236))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfirmationBackground_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfirmationBackground_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToPayment(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPayment
        // go to payment interface to choose payment method
        Payment X = new Payment();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToPayment

    private void backToprevious(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToprevious

        // back to browse make appointment interface
        MakeAppointment X;
        X = new MakeAppointment();
        X.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backToprevious

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Appointment_Info_Label;
    private javax.swing.JLabel BetsNo_Label;
    private javax.swing.JPanel ConfirmationBackground_Panel;
    private javax.swing.JButton Confirmation_Button;
    private javax.swing.JLabel Date_Label;
    private javax.swing.JLabel Page_Title_Label;
    private javax.swing.JLabel Services_Label;
    private javax.swing.JLabel Time_Label;
    private javax.swing.JLabel TotalPrice_Label;
    private javax.swing.JLabel backToprevious;
    // End of variables declaration//GEN-END:variables
}
