/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author renad
 */
public class ConfirmAppointment extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation_Button
     */
    public ConfirmAppointment() {
        initComponents();

        // set background 
        ImageIcon background = new ImageIcon("src\\Icons\\b2.jpg");
        background = new ImageIcon(background.getImage().getScaledInstance(Background.getWidth(), Background.getHeight(), Image.SCALE_DEFAULT));
        Background.setIcon(background);
        Background.repaint();

        // display appointment informations
        Appointment a = MakeAppointment.a;
        BetsNo_Label.setText(a.PetsNo());
        Date_Label.setText(a.Date());
        Time_Label.setText(a.time());
        Services_Label.setText(a.services());
        TotalPrice_Label.setText("Total Price : " + a.getTotalPrice() + " SR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConfirmationBackground_Panel = new javax.swing.JPanel();
        Page_Title_Label = new javax.swing.JLabel();
        Confirmation_Button = new javax.swing.JButton();
        Appointment_Info_Label = new javax.swing.JLabel();
        BetsNo_Label = new javax.swing.JLabel();
        Date_Label = new javax.swing.JLabel();
        Time_Label = new javax.swing.JLabel();
        Services_Label = new javax.swing.JLabel();
        TotalPrice_Label = new javax.swing.JLabel();
        backToprevious = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 550));
        setResizable(false);

        ConfirmationBackground_Panel.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmationBackground_Panel.setEnabled(false);
        ConfirmationBackground_Panel.setMinimumSize(new java.awt.Dimension(690, 450));
        ConfirmationBackground_Panel.setPreferredSize(new java.awt.Dimension(550, 550));
        ConfirmationBackground_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Page_Title_Label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Page_Title_Label.setText("Confirm Appointment");
        ConfirmationBackground_Panel.add(Page_Title_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        Confirmation_Button.setText("Confirm");
        Confirmation_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToPayment(evt);
            }
        });
        ConfirmationBackground_Panel.add(Confirmation_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 287, -1, -1));

        Appointment_Info_Label.setText("Appointment Information:");
        ConfirmationBackground_Panel.add(Appointment_Info_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 68, 160, -1));

        BetsNo_Label.setText("BetsNo");
        ConfirmationBackground_Panel.add(BetsNo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 256, -1));

        Date_Label.setText("Date");
        ConfirmationBackground_Panel.add(Date_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 275, -1));

        Time_Label.setText("Time");
        ConfirmationBackground_Panel.add(Time_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 363, -1));

        Services_Label.setText("Services");
        ConfirmationBackground_Panel.add(Services_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 423, -1));

        TotalPrice_Label.setText("Total Price");
        ConfirmationBackground_Panel.add(TotalPrice_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 423, -1));

        backToprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        backToprevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToprevious(evt);
            }
        });
        ConfirmationBackground_Panel.add(backToprevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        Background.setIconTextGap(0);
        Background.setPreferredSize(new java.awt.Dimension(550, 550));
        ConfirmationBackground_Panel.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfirmationBackground_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConfirmationBackground_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToPayment(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPayment
        // go to payment interface to choose payment method
        Payment X = new Payment();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToPayment

    private void backToprevious(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToprevious

        // back to browse make appointment interface
        MakeAppointment X;
        try {
            X = new MakeAppointment();
            X.setVisible(true);
            this.dispose();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ConfirmAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_backToprevious

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Appointment_Info_Label;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BetsNo_Label;
    private javax.swing.JPanel ConfirmationBackground_Panel;
    private javax.swing.JButton Confirmation_Button;
    private javax.swing.JLabel Date_Label;
    private javax.swing.JLabel Page_Title_Label;
    private javax.swing.JLabel Services_Label;
    private javax.swing.JLabel Time_Label;
    private javax.swing.JLabel TotalPrice_Label;
    private javax.swing.JLabel backToprevious;
    // End of variables declaration//GEN-END:variables
}
