package ProgramPackage;

import java.awt.Color;
import java.io.*;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author renad
 */
public class MakeAppointment extends javax.swing.JFrame {

    static File file;
    static PrintWriter p;
    static FileWriter f;
    static ArrayList<String> a = new ArrayList<>();

    /**
     * Creates new form VeterinaryClinic
     */
    public MakeAppointment() throws FileNotFoundException {
        initComponents();

        file = new File("AppointmentInfo.txt");
        p = new PrintWriter(file);

        // initialize clinic services
        Service.services.add(new Service("Health Care", 100, true));
        Service.services.add(new Service("Beauty Services", 150, true));
        Service.services.add(new Service("Insects Control", 80, true));
        Service.services.add(new Service("Training", 250, true));

        Health_Care_CheckBox.setText(Health_Care_CheckBox.getText() + " " + Service.services.get(0).getPrice() + "SR");
        Beauty_Services_CheckBox.setText(Beauty_Services_CheckBox.getText() + " " + Service.services.get(1).getPrice() + "SR");
        Insects_Control_CheckBox.setText(Insects_Control_CheckBox.getText() + " " + Service.services.get(2).getPrice() + "SR");
        Training_CheckBox.setText(Training_CheckBox.getText() + " " + Service.services.get(3).getPrice() + "SR");

    }

    static void file() throws IOException {
        //f = null;
        try {
            f = new FileWriter(file);
        } catch (IOException ex) {
            Logger.getLogger(MakeAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
        p = new PrintWriter(f);
        p.print(a);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MakeAppointmentBackground_Panel = new javax.swing.JPanel();
        PageTitle_Label = new javax.swing.JLabel();
        Services_Label = new javax.swing.JLabel();
        Health_Care_CheckBox = new javax.swing.JCheckBox();
        Beauty_Services_CheckBox = new javax.swing.JCheckBox();
        Insects_Control_CheckBox = new javax.swing.JCheckBox();
        appDate_Label = new javax.swing.JLabel();
        Training_CheckBox = new javax.swing.JCheckBox();
        pets_Label = new javax.swing.JLabel();
        noOfPets_Spinner = new javax.swing.JSpinner();
        nextStep_Button = new javax.swing.JButton();
        backToprevious_Button = new javax.swing.JButton();
        time_List = new javax.swing.JComboBox<>();
        appTime_Label = new javax.swing.JLabel();
        errorMessage_Label = new javax.swing.JLabel();
        appoDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MakeAppointmentBackground_Panel.setBackground(new java.awt.Color(255, 255, 255));
        MakeAppointmentBackground_Panel.setPreferredSize(new java.awt.Dimension(690, 460));

        PageTitle_Label.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        PageTitle_Label.setText("Make Appointment");

        Services_Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Services_Label.setText("Choose Services :");

        Health_Care_CheckBox.setText("Health Care");

        Beauty_Services_CheckBox.setText("Beauty Services");

        Insects_Control_CheckBox.setText("Insects Control");

        appDate_Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        appDate_Label.setText("Choose Appointment Date :");

        Training_CheckBox.setText("Training");

        pets_Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        pets_Label.setText("How many pets?");

        noOfPets_Spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        noOfPets_Spinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                noPet(evt);
            }
        });

        nextStep_Button.setText("Next Step");
        nextStep_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveAppointmentInfo(evt);
            }
        });

        backToprevious_Button.setBackground(new java.awt.Color(255, 255, 255));
        backToprevious_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        backToprevious_Button.setMaximumSize(new java.awt.Dimension(100, 100));
        backToprevious_Button.setMinimumSize(new java.awt.Dimension(50, 50));
        backToprevious_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToPrevious(evt);
            }
        });

        time_List.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "    :     AM/PM", "08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "01:00 PM", "02:00 PM", "03:00 PM", "04:00 PM" }));

        appTime_Label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        appTime_Label.setText("Choose Appointment Time :");

        javax.swing.GroupLayout MakeAppointmentBackground_PanelLayout = new javax.swing.GroupLayout(MakeAppointmentBackground_Panel);
        MakeAppointmentBackground_Panel.setLayout(MakeAppointmentBackground_PanelLayout);
        MakeAppointmentBackground_PanelLayout.setHorizontalGroup(
            MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backToprevious_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Services_Label)
                            .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                                .addComponent(pets_Label)
                                .addGap(32, 32, 32)
                                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PageTitle_Label)
                                    .addComponent(noOfPets_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(appTime_Label, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(appDate_Label, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(time_List, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(appoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(errorMessage_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(nextStep_Button))
                    .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Insects_Control_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Health_Care_CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Beauty_Services_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Training_CheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        MakeAppointmentBackground_PanelLayout.setVerticalGroup(
            MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backToprevious_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PageTitle_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfPets_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pets_Label))
                .addGap(12, 12, 12)
                .addComponent(Services_Label)
                .addGap(18, 18, 18)
                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Health_Care_CheckBox)
                    .addComponent(Beauty_Services_CheckBox))
                .addGap(7, 7, 7)
                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insects_Control_CheckBox)
                    .addComponent(Training_CheckBox))
                .addGap(26, 26, 26)
                .addGroup(MakeAppointmentBackground_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                        .addComponent(appDate_Label)
                        .addGap(32, 32, 32)
                        .addComponent(appTime_Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(errorMessage_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nextStep_Button))
                    .addGroup(MakeAppointmentBackground_PanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(time_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(appoDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MakeAppointmentBackground_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MakeAppointmentBackground_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BCboxActionPerformed

    private void noPet(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_noPet
        String spinner = "catch Value";
        Integer myint = (Integer) noOfPets_Spinner.getValue();
        spinner = myint.toString();
        a.add(spinner);
    }//GEN-LAST:event_noPet

    // --------- Check if user fill in correctly all the requirements ---------
    private boolean checkAppoinmentInfo() {
        Services_Label.setForeground(Color.black);
        appDate_Label.setForeground(Color.black);
        appTime_Label.setForeground(Color.black);
        errorMessage_Label.setText(" ");

        boolean validInfo = true;

        if (validInfo == true) {

            if (!Health_Care_CheckBox.isSelected() && !Beauty_Services_CheckBox.isSelected()
                    && !Insects_Control_CheckBox.isSelected() && !Training_CheckBox.isSelected()) {
                Services_Label.setForeground(Color.red);
                displayErrorMassage();
                validInfo = false;
            }

            if (appoDateChooser.getDate() == null) {
                appDate_Label.setForeground(Color.red);
                displayErrorMassage();
                validInfo = false;
            } else if (checkDate(appoDateChooser.getDate()) == false) {
                appDate_Label.setForeground(Color.red);
                errorMessage_Label.setText("Date must not be in the past, please choose different date");
                errorMessage_Label.setForeground(Color.red);
                validInfo = false;
            }

            if (time_List.getSelectedIndex() == 0) {
                appTime_Label.setForeground(Color.red);
                displayErrorMassage();
                validInfo = false;
            }
        }

        return validInfo;
    }

    // --------- check if selected date in past ---------
    private boolean checkDate(Date selectedDate) {
        boolean checker = true;

        Date today = new Date();
        int currentDay = today.getDate();
        int currentMonth = today.getMonth();

        int selectedDay = appoDateChooser.getDate().getDate();
        int selectedMonth = appoDateChooser.getDate().getMonth();

        if (currentDay == selectedDay && currentMonth == selectedMonth) {
            checker = true;
        } else if (appoDateChooser.getDate().before(today)) {
            checker = false;
        }

        return checker;
    }

    // --------- display the error massage for empty feild ---------
    private void displayErrorMassage() {
        errorMessage_Label.setText("Please fill in all the requirements to confirm the appointment");
        errorMessage_Label.setForeground(Color.red);
    }

    // --------- save the appointment information on the clinc appointment list ---------
    private void saveAppointmentInfo(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveAppointmentInfo
        if (checkAppoinmentInfo() == true) {

            Appointment a = new Appointment();
            a.setNoPet((int) noOfPets_Spinner.getValue());
            a.setDate(appoDateChooser.getDate());
            a.setTime(time_List.getItemAt(time_List.getSelectedIndex()));

            if (Health_Care_CheckBox.isSelected()) {
                a.addService(Service.services.get(0));
                a.setTotalPrice(a.getTotalPrice() + Service.services.get(0).getPrice());
            }
            if (Beauty_Services_CheckBox.isSelected()) {
                a.addService(Service.services.get(1));
                a.setTotalPrice(a.getTotalPrice() + Service.services.get(1).getPrice());
            }
            if (Insects_Control_CheckBox.isSelected()) {
                a.addService(Service.services.get(2));
                a.setTotalPrice(a.getTotalPrice() + (Service.services.get(2).getPrice()));
            }
            if (Training_CheckBox.isSelected()) {
                a.addService(Service.services.get(3));
                a.setTotalPrice(a.getTotalPrice() + Service.services.get(3).getPrice());
            }

            a.setTotalPrice(a.getTotalPrice() * a.getNoPet());
            p.print(a);

            ConfirmAppointment X = new ConfirmAppointment(a);
            X.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_saveAppointmentInfo

    private void backToPrevious(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToPrevious
        // back to browse services interface

        //*** not implemented yet ***
    }//GEN-LAST:event_backToPrevious

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MakeAppointment().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(MakeAppointment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Beauty_Services_CheckBox;
    private javax.swing.JCheckBox Health_Care_CheckBox;
    private javax.swing.JCheckBox Insects_Control_CheckBox;
    private javax.swing.JPanel MakeAppointmentBackground_Panel;
    private javax.swing.JLabel PageTitle_Label;
    private javax.swing.JLabel Services_Label;
    private javax.swing.JCheckBox Training_CheckBox;
    private javax.swing.JLabel appDate_Label;
    private javax.swing.JLabel appTime_Label;
    private com.toedter.calendar.JDateChooser appoDateChooser;
    private javax.swing.JButton backToprevious_Button;
    private javax.swing.JLabel errorMessage_Label;
    private javax.swing.JButton nextStep_Button;
    private javax.swing.JSpinner noOfPets_Spinner;
    private javax.swing.JLabel pets_Label;
    private javax.swing.JComboBox<String> time_List;
    // End of variables declaration//GEN-END:variables
}
