/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Bushra
 */
public class PayByCreditCard extends javax.swing.JFrame {

    /**
     * Creates new form PayByCreditCard
     */
    public PayByCreditCard() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Gray = new javax.swing.JPanel();
        Background_White = new javax.swing.JPanel();
        nextBtn = new javax.swing.JButton();
        PageTitle_Label = new javax.swing.JLabel();
        Back_label = new javax.swing.JLabel();
        CardNum_Label = new javax.swing.JLabel();
        CreditCard = new javax.swing.JTextField();
        Card_Holder_Label = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Error_massage = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();
        CVV_Label = new javax.swing.JLabel();
        Error_Message_Name = new javax.swing.JLabel();
        expiration_date = new javax.swing.JLabel();
        Example_Label = new javax.swing.JLabel();
        Error_Message_Date = new javax.swing.JLabel();
        CVV = new javax.swing.JTextField();
        Error_Message_cvv = new javax.swing.JLabel();
        Card_Holder_Label1 = new javax.swing.JLabel();
        Error_Message_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 730));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        Background_Gray.setBackground(new java.awt.Color(249, 249, 249));
        Background_Gray.setLayout(null);

        Background_White.setBackground(new java.awt.Color(255, 255, 255));

        nextBtn.setText("Next");
        nextBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goTo_Next(evt);
            }
        });
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Background_WhiteLayout = new javax.swing.GroupLayout(Background_White);
        Background_White.setLayout(Background_WhiteLayout);
        Background_WhiteLayout.setHorizontalGroup(
            Background_WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_WhiteLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        Background_WhiteLayout.setVerticalGroup(
            Background_WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_WhiteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(nextBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background_Gray.add(Background_White);
        Background_White.setBounds(0, 600, 380, 80);

        PageTitle_Label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PageTitle_Label.setForeground(new java.awt.Color(51, 0, 102));
        PageTitle_Label.setText("Credit Card");
        Background_Gray.add(PageTitle_Label);
        PageTitle_Label.setBounds(70, 30, 190, 37);

        Back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_arrow.png"))); // NOI18N
        Back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_labelbackTo_pre(evt);
            }
        });
        Background_Gray.add(Back_label);
        Back_label.setBounds(10, 10, 14, 24);

        CardNum_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CardNum_Label.setText("Card Number ");
        Background_Gray.add(CardNum_Label);
        CardNum_Label.setBounds(20, 270, 140, 17);

        CreditCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditCardActionPerformed(evt);
            }
        });
        Background_Gray.add(CreditCard);
        CreditCard.setBounds(20, 290, 290, 40);

        Card_Holder_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Card_Holder_Label.setText("Enter Card Detalis");
        Background_Gray.add(Card_Holder_Label);
        Card_Holder_Label.setBounds(20, 100, 160, 17);
        Background_Gray.add(Name);
        Name.setBounds(20, 160, 290, 40);

        Error_massage.setFont(new java.awt.Font("Aldhabi", 1, 18)); // NOI18N
        Background_Gray.add(Error_massage);
        Error_massage.setBounds(20, 340, 290, 50);
        Background_Gray.add(Date);
        Date.setBounds(20, 430, 110, 40);

        CVV_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CVV_Label.setText("CVV  ");
        Background_Gray.add(CVV_Label);
        CVV_Label.setBounds(170, 410, 130, 17);

        Error_Message_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Background_Gray.add(Error_Message_Name);
        Error_Message_Name.setBounds(20, 210, 120, 0);

        expiration_date.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        expiration_date.setText("Expriation Date  ");
        Background_Gray.add(expiration_date);
        expiration_date.setBounds(20, 410, 150, 17);

        Example_Label.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Example_Label.setText("example: mm/yy");
        Background_Gray.add(Example_Label);
        Example_Label.setBounds(20, 490, 150, 17);

        Error_Message_Date.setFont(new java.awt.Font("Aldhabi", 1, 18)); // NOI18N
        Background_Gray.add(Error_Message_Date);
        Error_Message_Date.setBounds(20, 510, 310, 50);

        CVV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CVVKeyPressed(evt);
            }
        });
        Background_Gray.add(CVV);
        CVV.setBounds(170, 430, 110, 40);

        Error_Message_cvv.setFont(new java.awt.Font("Aldhabi", 1, 18)); // NOI18N
        Background_Gray.add(Error_Message_cvv);
        Error_Message_cvv.setBounds(160, 470, 180, 50);

        Card_Holder_Label1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Card_Holder_Label1.setText("Name on Card ");
        Background_Gray.add(Card_Holder_Label1);
        Card_Holder_Label1.setBounds(20, 140, 160, 17);

        Error_Message_name.setFont(new java.awt.Font("Aldhabi", 1, 18)); // NOI18N
        Background_Gray.add(Error_Message_name);
        Error_Message_name.setBounds(20, 210, 290, 50);

        getContentPane().add(Background_Gray);
        Background_Gray.setBounds(0, 0, 350, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CVVKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CVVKeyPressed

    }//GEN-LAST:event_CVVKeyPressed

    private void CreditCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditCardActionPerformed

    }//GEN-LAST:event_CreditCardActionPerformed

    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed

    }//GEN-LAST:event_nextBtnActionPerformed

    private void goTo_Next(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goTo_Next
        boolean validCardNum = checkCreditNumber();
        boolean validName = checkName();
        boolean validCvv = checkCVV();
        boolean validDate = CardDate();
        boolean validInfo = validCardNum && validName && validCvv && validDate;
        if (validInfo == true) {
            SuccessfulComplete_Interface X = new SuccessfulComplete_Interface();
            X.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_goTo_Next

    private void Back_labelbackTo_pre(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_labelbackTo_pre
        Browse_Services X = new Browse_Services();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_labelbackTo_pre

    private boolean checkCVV() {
        boolean valid = true;
        String Cvv = CVV.getText();
        Error_Message_cvv.setText(" ");

        if (Cvv.matches("[0-9]+") && Cvv.length() == 3) {
            valid = true;
            Error_Message_cvv.setText(" ");
        } else {
            valid = false;
            Error_Message_cvv.setText("Security code is invalid");
            Error_Message_cvv.setForeground(Color.red);
        }

        return valid;
    }

    private boolean checkName() {
        boolean valid = true;

        String Name_Holder = Name.getText();
        Error_Message_name.setText(" ");

        if (Name_Holder.matches("[a-zA-Z- ]+") && !"".equals(Name_Holder.trim())) {

        } else if (Name_Holder.equals(null) || "".equals(Name_Holder.trim())) {

            valid = false;
            Error_Message_name.setText("Please Enter Your Name");
            Error_Message_name.setForeground(Color.red);

        } else {
            valid = false;
            Error_Message_name.setText("Please Enter Your Name In The Correct Way");
            Error_Message_name.setForeground(Color.red);
        }
        return valid;
    }

    private boolean CardDate() {
        boolean valid = true;

        String userInput = Date.getText();
        Error_Message_Date.setText(" ");

        if (userInput.trim().equals("")) {

            valid = false;
            Error_Message_Date.setText("Enter expiry date");
            Error_Message_Date.setForeground(Color.red);

        } else {

            SimpleDateFormat dateFormat = new SimpleDateFormat("MM/yy");
            dateFormat.setLenient(false);
            try {
                Date date = dateFormat.parse(userInput);
                Error_Message_Date.setText("");

            } catch (ParseException e) {
                valid = false;
                Error_Message_Date.setText(userInput + " is Invalid Date format");
                Error_Message_Date.setForeground(Color.red);
            }
        }

        return valid;
    }

    private boolean checkCreditNumber() {
        boolean valid = true;

        String Credit = CreditCard.getText();
        Error_massage.setText(" ");

        if (Credit.trim().equals("")) {

            valid = false;
            Error_massage.setText("Enter your card number");
            Error_massage.setForeground(Color.red);

        } else if (Credit.matches("[0-9]+") && Credit.length() == 16) {
            Error_massage.setText(" ");

        } else {

            valid = false;
            Error_massage.setText("Enter a 16-digit card number");
            Error_massage.setForeground(Color.red);

        }
        return valid;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PayByCreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PayByCreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PayByCreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PayByCreditCard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PayByCreditCard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back_label;
    private javax.swing.JPanel Background_Gray;
    private javax.swing.JPanel Background_Gray2;
    private javax.swing.JPanel Background_Gray3;
    private javax.swing.JPanel Background_Gray4;
    private javax.swing.JPanel Background_White;
    private javax.swing.JPanel Background_White2;
    private javax.swing.JPanel Background_White3;
    private javax.swing.JPanel Background_White4;
    private javax.swing.JTextField CVV;
    private javax.swing.JLabel CVV_Label;
    private javax.swing.JLabel CardNum_Label;
    private javax.swing.JLabel Card_Holder_Label;
    private javax.swing.JLabel Card_Holder_Label1;
    private javax.swing.JTextField CreditCard;
    private javax.swing.JTextField Date;
    private javax.swing.JLabel Error_Message_Date;
    private javax.swing.JLabel Error_Message_Name;
    private javax.swing.JLabel Error_Message_cvv;
    private javax.swing.JLabel Error_Message_name;
    private javax.swing.JLabel Error_massage;
    private javax.swing.JLabel Example_Label;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel PageTitle_Label;
    private javax.swing.JLabel expiration_date;
    private javax.swing.JButton nextBtn;
    private javax.swing.JButton nextBtn2;
    private javax.swing.JButton nextBtn3;
    private javax.swing.JButton nextBtn4;
    // End of variables declaration//GEN-END:variables
}
