/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author renad
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background_Gray = new javax.swing.JPanel();
        Background_White = new javax.swing.JPanel();
        Home_Icon_Label = new javax.swing.JLabel();
        PageTitle_Label = new javax.swing.JLabel();
        Back_label = new javax.swing.JLabel();
        paymentMassage = new javax.swing.JLabel();
        CreditCard = new javax.swing.JLabel();
        Bed_OrangeSquareLabel = new javax.swing.JLabel();
        Cash = new javax.swing.JLabel();
        Collar_OrangeSquareLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(340, 720));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        Background_Gray.setBackground(new java.awt.Color(249, 249, 249));
        Background_Gray.setLayout(null);

        Background_White.setBackground(new java.awt.Color(255, 255, 255));

        Home_Icon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        Home_Icon_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Home_Icon_LabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Background_WhiteLayout = new javax.swing.GroupLayout(Background_White);
        Background_White.setLayout(Background_WhiteLayout);
        Background_WhiteLayout.setHorizontalGroup(
            Background_WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Background_WhiteLayout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(Home_Icon_Label)
                .addGap(190, 190, 190))
        );
        Background_WhiteLayout.setVerticalGroup(
            Background_WhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Background_WhiteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Home_Icon_Label)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        Background_Gray.add(Background_White);
        Background_White.setBounds(0, 600, 380, 80);

        PageTitle_Label.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PageTitle_Label.setForeground(new java.awt.Color(51, 0, 102));
        PageTitle_Label.setText("Payment");
        Background_Gray.add(PageTitle_Label);
        PageTitle_Label.setBounds(90, 30, 190, 37);

        Back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_arrow.png"))); // NOI18N
        Back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_labelbackTo_pre(evt);
            }
        });
        Background_Gray.add(Back_label);
        Back_label.setBounds(10, 10, 14, 24);

        paymentMassage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        paymentMassage.setText("Choose Payment Method");
        Background_Gray.add(paymentMassage);
        paymentMassage.setBounds(30, 110, 210, 50);

        CreditCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/creditcard.png"))); // NOI18N
        CreditCard.setToolTipText("");
        CreditCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToPay_byCreditCard(evt);
            }
        });
        Background_Gray.add(CreditCard);
        CreditCard.setBounds(130, 220, 80, 100);

        Bed_OrangeSquareLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/square_purple.png"))); // NOI18N
        Background_Gray.add(Bed_OrangeSquareLabel);
        Bed_OrangeSquareLabel.setBounds(90, 140, 149, 260);

        Cash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cash_1.png"))); // NOI18N
        Cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToPay_byCash(evt);
            }
        });
        Background_Gray.add(Cash);
        Cash.setBounds(130, 420, 70, 100);

        Collar_OrangeSquareLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/square_purple.png"))); // NOI18N
        Background_Gray.add(Collar_OrangeSquareLabel);
        Collar_OrangeSquareLabel.setBounds(90, 350, 149, 240);

        getContentPane().add(Background_Gray);
        Background_Gray.setBounds(0, 0, 390, 740);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToPay_byCreditCard(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPay_byCreditCard
        // go to pay by credit card interface to fill in card information
        PayByCreditCard X = new PayByCreditCard();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToPay_byCreditCard

    private void goToPay_byCash(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPay_byCash
        // go to bill interface
        SuccessfulComplete_Interface X = new SuccessfulComplete_Interface();
        X.setVisible(true);
        this.dispose();
        //*** not implemented yet ***
    }//GEN-LAST:event_goToPay_byCash

    private void Back_labelbackTo_pre(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_labelbackTo_pre
        Date_Time X = new Date_Time();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_labelbackTo_pre

    private void Home_Icon_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Home_Icon_LabelMouseClicked
        Browse_Services X = new Browse_Services();
        X.setVisible(true);
        this.dispose();    }//GEN-LAST:event_Home_Icon_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back_label;
    private javax.swing.JPanel Background_Gray;
    private javax.swing.JPanel Background_White;
    private javax.swing.JLabel Bed_OrangeSquareLabel;
    private javax.swing.JLabel Cash;
    private javax.swing.JLabel Collar_OrangeSquareLabel;
    private javax.swing.JLabel CreditCard;
    private javax.swing.JLabel Home_Icon_Label;
    private javax.swing.JLabel PageTitle_Label;
    private javax.swing.JLabel paymentMassage;
    // End of variables declaration//GEN-END:variables
}
