/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author renad
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
        
        // set background 
        ImageIcon background = new ImageIcon("src\\Icons\\b2.jpg");
        background = new ImageIcon(background.getImage().getScaledInstance(Background.getWidth(), Background.getHeight(), Image.SCALE_DEFAULT));
        Background.setIcon(background);
        Background.repaint();
        
        ImageIcon icon;
        // set credit card icon
        icon = new ImageIcon("src\\Icons\\credit-card.png");
        icon = new ImageIcon(icon.getImage().getScaledInstance(CreditCard.getWidth(), CreditCard.getHeight(), Image.SCALE_DEFAULT));
        CreditCard.setIcon(icon);
        CreditCard.repaint();
        
        // set cash icon
        icon = new ImageIcon("src\\Icons\\cash.png");
        icon = new ImageIcon(icon.getImage().getScaledInstance(Cash.getWidth(), Cash.getHeight(), Image.SCALE_DEFAULT));
        Cash.setIcon(icon);
        Cash.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGr_Panel = new java.awt.Panel();
        Credit_card_label = new javax.swing.JLabel();
        CreditCard = new javax.swing.JLabel();
        Cash = new javax.swing.JLabel();
        paymentMassage = new javax.swing.JLabel();
        backToprevious = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Credit_card_label.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Credit_card_label.setText("Payment");
        Credit_card_label.setToolTipText("");

        CreditCard.setText("jLabel1");
        CreditCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToPay_byCreditCard(evt);
            }
        });

        Cash.setText("jLabel1");
        Cash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToPay_byCash(evt);
            }
        });

        paymentMassage.setText("Pleas choose How to Pay");

        backToprevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
        backToprevious.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToprevious(evt);
            }
        });

        Background.setIconTextGap(0);
        Background.setPreferredSize(new java.awt.Dimension(550, 550));

        javax.swing.GroupLayout BackGr_PanelLayout = new javax.swing.GroupLayout(BackGr_Panel);
        BackGr_Panel.setLayout(BackGr_PanelLayout);
        BackGr_PanelLayout.setHorizontalGroup(
            BackGr_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(paymentMassage))
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(Credit_card_label))
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(CreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backToprevious)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        BackGr_PanelLayout.setVerticalGroup(
            BackGr_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(paymentMassage))
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(Credit_card_label))
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(CreditCard, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(BackGr_PanelLayout.createSequentialGroup()
                .addGap(260, 260, 260)
                .addComponent(Cash, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(backToprevious)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGr_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BackGr_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goToPay_byCreditCard(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPay_byCreditCard
        // go to pay by credit card interface to fill in card information
        PayByCreditCard X = new PayByCreditCard();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToPay_byCreditCard

    private void goToPay_byCash(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToPay_byCash
        // go to bill interface
        SuccessfulComplete_Interface X = new SuccessfulComplete_Interface();
        X.setVisible(true);
        this.dispose();
        //*** not implemented yet ***
    }//GEN-LAST:event_goToPay_byCash

    private void backToprevious(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToprevious
        // back to payment interface
        ConfirmAppointment X = new ConfirmAppointment();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backToprevious

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel BackGr_Panel;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Cash;
    private javax.swing.JLabel CreditCard;
    private javax.swing.JLabel Credit_card_label;
    private javax.swing.JLabel backToprevious;
    private javax.swing.JLabel paymentMassage;
    // End of variables declaration//GEN-END:variables
}
