/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;


/**
 *
 * @author alano
 */
public class PetCareServices extends javax.swing.JFrame {

    /**
     * Creates new form PetCareServices
     */
    public PetCareServices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TrainPrice_Label = new javax.swing.JLabel();
        InsectPrice_label = new javax.swing.JLabel();
        BeautyPrice_Label = new javax.swing.JLabel();
        HealthPrice_label = new javax.swing.JLabel();
        MakeAppointmen_Label = new javax.swing.JLabel();
        Back_label = new javax.swing.JLabel();
        PageTitle_Label1 = new javax.swing.JLabel();
        HealthIcon_Label = new javax.swing.JLabel();
        BeuatyIcon_Label = new javax.swing.JLabel();
        InsectIcon_Label = new javax.swing.JLabel();
        TrainIcon_Label = new javax.swing.JLabel();
        HealthCare_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BeautyServices_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InsectControl_Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Train_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GO_MakeAppointment_Label = new javax.swing.JLabel();
        HomeIcon_label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        TrainPrice_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TrainPrice_Label.setForeground(new java.awt.Color(255, 255, 255));
        TrainPrice_Label.setText("250");
        getContentPane().add(TrainPrice_Label);
        TrainPrice_Label.setBounds(170, 450, 39, 25);

        InsectPrice_label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        InsectPrice_label.setForeground(new java.awt.Color(255, 255, 255));
        InsectPrice_label.setText("150");
        getContentPane().add(InsectPrice_label);
        InsectPrice_label.setBounds(170, 350, 39, 25);

        BeautyPrice_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BeautyPrice_Label.setForeground(new java.awt.Color(255, 255, 255));
        BeautyPrice_Label.setText("80");
        getContentPane().add(BeautyPrice_Label);
        BeautyPrice_Label.setBounds(180, 250, 26, 25);

        HealthPrice_label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        HealthPrice_label.setForeground(new java.awt.Color(255, 255, 255));
        HealthPrice_label.setText("100");
        getContentPane().add(HealthPrice_label);
        HealthPrice_label.setBounds(170, 160, 39, 25);

        MakeAppointmen_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MakeAppointmen_Label.setForeground(new java.awt.Color(51, 0, 102));
        MakeAppointmen_Label.setText("Make Appointment");
        MakeAppointmen_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GO_MakeAppointment_LabelMouseClicked(evt);
            }
        });
        getContentPane().add(MakeAppointmen_Label);
        MakeAppointmen_Label.setBounds(80, 540, 220, 30);

        Back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_arrow.png"))); // NOI18N
        Back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_labelbackTo_pre(evt);
            }
        });
        getContentPane().add(Back_label);
        Back_label.setBounds(10, 10, 14, 24);

        PageTitle_Label1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PageTitle_Label1.setForeground(new java.awt.Color(51, 0, 102));
        PageTitle_Label1.setText("Services");
        getContentPane().add(PageTitle_Label1);
        PageTitle_Label1.setBounds(40, 50, 190, 37);

        HealthIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/P1.png"))); // NOI18N
        getContentPane().add(HealthIcon_Label);
        HealthIcon_Label.setBounds(40, 110, 82, 81);

        BeuatyIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pic3.png"))); // NOI18N
        getContentPane().add(BeuatyIcon_Label);
        BeuatyIcon_Label.setBounds(40, 210, 79, 79);

        InsectIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pic4.png"))); // NOI18N
        getContentPane().add(InsectIcon_Label);
        InsectIcon_Label.setBounds(30, 300, 100, 80);

        TrainIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pic5.png"))); // NOI18N
        getContentPane().add(TrainIcon_Label);
        TrainIcon_Label.setBounds(30, 400, 80, 80);

        HealthCare_label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        HealthCare_label.setForeground(new java.awt.Color(255, 255, 255));
        HealthCare_label.setText("Health Care");
        getContentPane().add(HealthCare_label);
        HealthCare_label.setBounds(130, 130, 118, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 110, 284, 89);

        BeautyServices_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BeautyServices_Label.setForeground(new java.awt.Color(255, 255, 255));
        BeautyServices_Label.setText("Beauty Services");
        getContentPane().add(BeautyServices_Label);
        BeautyServices_Label.setBounds(120, 220, 162, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 199, 284, 100);

        InsectControl_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        InsectControl_Label.setForeground(new java.awt.Color(255, 255, 255));
        InsectControl_Label.setText("Insect control");
        getContentPane().add(InsectControl_Label);
        InsectControl_Label.setBounds(130, 320, 141, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 299, 284, 90);

        Train_label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Train_label.setForeground(new java.awt.Color(255, 255, 255));
        Train_label.setText("Training");
        getContentPane().add(Train_label);
        Train_label.setBounds(140, 420, 84, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 400, 284, 89);

        GO_MakeAppointment_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/next.png"))); // NOI18N
        GO_MakeAppointment_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GO_MakeAppointment_LabelMouseClicked(evt);
            }
        });
        getContentPane().add(GO_MakeAppointment_Label);
        GO_MakeAppointment_Label.setBounds(280, 540, 14, 24);

        HomeIcon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        HomeIcon_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeIcon_labelMouseClicked(evt);
            }
        });
        getContentPane().add(HomeIcon_label);
        HomeIcon_label.setBounds(140, 630, 35, 33);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Packground_gray.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 330, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_labelbackTo_pre(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_labelbackTo_pre
        Browse_Services X = new Browse_Services();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_labelbackTo_pre

    private void GO_MakeAppointment_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GO_MakeAppointment_LabelMouseClicked
        MakeAppointment GO_MakeAppointment = null;
        GO_MakeAppointment = new MakeAppointment();
        GO_MakeAppointment.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_GO_MakeAppointment_LabelMouseClicked

    private void HomeIcon_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeIcon_labelMouseClicked
        Browse_Services X = new Browse_Services();
        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeIcon_labelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetCareServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back_label;
    private javax.swing.JLabel BeautyPrice_Label;
    private javax.swing.JLabel BeautyServices_Label;
    private javax.swing.JLabel BeuatyIcon_Label;
    private javax.swing.JLabel GO_MakeAppointment_Label;
    private javax.swing.JLabel HealthCare_label;
    private javax.swing.JLabel HealthIcon_Label;
    private javax.swing.JLabel HealthPrice_label;
    private javax.swing.JLabel HomeIcon_label;
    private javax.swing.JLabel InsectControl_Label;
    private javax.swing.JLabel InsectIcon_Label;
    private javax.swing.JLabel InsectPrice_label;
    private javax.swing.JLabel MakeAppointmen_Label;
    private javax.swing.JLabel PageTitle_Label1;
    private javax.swing.JLabel TrainIcon_Label;
    private javax.swing.JLabel TrainPrice_Label;
    private javax.swing.JLabel Train_label;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
