/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramPackage;

/**
 *
 * @author alano
 */
public class PetCareServices extends javax.swing.JFrame {

    /**
     * Creates new form PetCareServices
     */
    public PetCareServices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MakeAppointmen_Label = new javax.swing.JLabel();
        Back_label = new javax.swing.JLabel();
        PageTitle_Label1 = new javax.swing.JLabel();
        HealthIcon_Label = new javax.swing.JLabel();
        BeuatyIcon_Label = new javax.swing.JLabel();
        InsectIcon_Label = new javax.swing.JLabel();
        TrainIcon_Label = new javax.swing.JLabel();
        HealthCare_label = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BeautyServices_Label = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InsectControl_Label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Train_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        GO_MakeAppointment_Label = new javax.swing.JLabel();
        HomeIcon_label = new javax.swing.JLabel();
        CartIcon_Label = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MakeAppointmen_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        MakeAppointmen_Label.setForeground(new java.awt.Color(51, 0, 102));
        MakeAppointmen_Label.setText("Make Appointment");
        getContentPane().add(MakeAppointmen_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 220, 60));

        Back_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back_arrow.png"))); // NOI18N
        Back_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Back_labelbackTo_pre(evt);
            }
        });
        getContentPane().add(Back_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        PageTitle_Label1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        PageTitle_Label1.setForeground(new java.awt.Color(51, 0, 102));
        PageTitle_Label1.setText("Services");
        getContentPane().add(PageTitle_Label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 190, -1));

        HealthIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/P1.png"))); // NOI18N
        getContentPane().add(HealthIcon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        BeuatyIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pic3.png"))); // NOI18N
        getContentPane().add(BeuatyIcon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        InsectIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pic4.png"))); // NOI18N
        getContentPane().add(InsectIcon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 100, 80));

        TrainIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Pic5.png"))); // NOI18N
        getContentPane().add(TrainIcon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        HealthCare_label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        HealthCare_label.setForeground(new java.awt.Color(255, 255, 255));
        HealthCare_label.setText("Health Care");
        getContentPane().add(HealthCare_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        BeautyServices_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        BeautyServices_Label.setForeground(new java.awt.Color(255, 255, 255));
        BeautyServices_Label.setText("Beauty Services");
        getContentPane().add(BeautyServices_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 199, -1, 100));

        InsectControl_Label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        InsectControl_Label.setForeground(new java.awt.Color(255, 255, 255));
        InsectControl_Label.setText("Insect control");
        getContentPane().add(InsectControl_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 299, -1, 90));

        Train_label.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Train_label.setForeground(new java.awt.Color(255, 255, 255));
        Train_label.setText("Training");
        getContentPane().add(Train_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/BOX_PU.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        GO_MakeAppointment_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/next.png"))); // NOI18N
        GO_MakeAppointment_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GO_MakeAppointment_LabelMouseClicked(evt);
            }
        });
        getContentPane().add(GO_MakeAppointment_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 540, -1, -1));

        HomeIcon_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home.png"))); // NOI18N
        getContentPane().add(HomeIcon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 630, -1, -1));

        CartIcon_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/cart_dark.png"))); // NOI18N
        getContentPane().add(CartIcon_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Packground_gray.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Back_labelbackTo_pre(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Back_labelbackTo_pre
        Browse_Services X = new Browse_Services();

        X.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Back_labelbackTo_pre

    private void GO_MakeAppointment_LabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GO_MakeAppointment_LabelMouseClicked


    }//GEN-LAST:event_GO_MakeAppointment_LabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetCareServices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetCareServices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back_label;
    private javax.swing.JLabel BeautyServices_Label;
    private javax.swing.JLabel BeuatyIcon_Label;
    private javax.swing.JLabel CartIcon_Label;
    private javax.swing.JLabel GO_MakeAppointment_Label;
    private javax.swing.JLabel HealthCare_label;
    private javax.swing.JLabel HealthIcon_Label;
    private javax.swing.JLabel HomeIcon_label;
    private javax.swing.JLabel InsectControl_Label;
    private javax.swing.JLabel InsectIcon_Label;
    private javax.swing.JLabel MakeAppointmen_Label;
    private javax.swing.JLabel PageTitle_Label1;
    private javax.swing.JLabel TrainIcon_Label;
    private javax.swing.JLabel Train_label;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
